/** Generated by YAKINDU Statechart Tools code generator. */
package microwave.microwave;

import microwave.ITimer;

public class MicrowaveStatemachine implements IMicrowaveStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private SCInterfaceOperationCallback operationCallback;
		
		public void setSCInterfaceOperationCallback(
				SCInterfaceOperationCallback operationCallback) {
			this.operationCallback = operationCallback;
		}
		private boolean high;
		
		
		public void raiseHigh() {
			high = true;
			runCycle();
		}
		
		private boolean low;
		
		
		public void raiseLow() {
			low = true;
			runCycle();
		}
		
		private boolean digit;
		
		private long digitValue;
		
		
		public void raiseDigit(final long value) {
			digitValue = value;
			digit = true;
			runCycle();
		}
		protected long getDigitValue() {
			if (! digit ) 
				throw new IllegalStateException("Illegal event value access. Event Digit is not raised!");
			return digitValue;
		}
		
		private boolean timer;
		
		
		public void raiseTimer() {
			timer = true;
			runCycle();
		}
		
		private boolean start;
		
		
		public void raiseStart() {
			start = true;
			runCycle();
		}
		
		private boolean stop;
		
		
		public void raiseStop() {
			stop = true;
			runCycle();
		}
		
		private boolean open;
		
		
		public void raiseOpen() {
			open = true;
			runCycle();
		}
		
		private boolean close;
		
		
		public void raiseClose() {
			close = true;
			runCycle();
		}
		
		private long power;
		
		public long getPower() {
			return power;
		}
		
		public void setPower(long value) {
			this.power = value;
		}
		
		protected void clearEvents() {
			high = false;
			low = false;
			digit = false;
			timer = false;
			start = false;
			stop = false;
			open = false;
			close = false;
		}
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		microwave_OpenDoor,
		microwave_closed_microwave,
		microwave_closed_microwave_r1_HighPower,
		microwave_closed_microwave_r1_LowPower,
		microwave_closed_microwave_r1_setTime,
		microwave_closed_microwave_r1_Cooking,
		microwave_closed_microwave_r1_Init,
		microwave_closed_microwave_r1_Finished,
		microwave_closed_microwave_r1_Finished_r1_BeepOnState,
		microwave_closed_microwave_r1_Finished_r1_BeepOffState,
		$NullState$
	};
	
	private State[] historyVector = new State[2];
	private final State[] stateVector = new State[1];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[4];
	
	private long timeVariable;
	
	protected long getTimeVariable() {
		return timeVariable;
	}
	
	protected void setTimeVariable(long value) {
		this.timeVariable = value;
	}
	
	
	public MicrowaveStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		if (this.sCInterface.operationCallback == null) {
			throw new IllegalStateException("Operation callback for interface sCInterface must be set.");
		}
		
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NullState$;
		}
		for (int i = 0; i < 2; i++) {
			historyVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
		sCInterface.setPower(0);
		
		setTimeVariable(0);
	}
	
	public void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_Microwave_default();
	}
	
	public void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		clearOutEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case microwave_OpenDoor:
				microwave_OpenDoor_react(true);
				break;
			case microwave_closed_microwave_r1_HighPower:
				microwave_closed_microwave_r1_HighPower_react(true);
				break;
			case microwave_closed_microwave_r1_LowPower:
				microwave_closed_microwave_r1_LowPower_react(true);
				break;
			case microwave_closed_microwave_r1_setTime:
				microwave_closed_microwave_r1_setTime_react(true);
				break;
			case microwave_closed_microwave_r1_Cooking:
				microwave_closed_microwave_r1_Cooking_react(true);
				break;
			case microwave_closed_microwave_r1_Init:
				microwave_closed_microwave_r1_Init_react(true);
				break;
			case microwave_closed_microwave_r1_Finished_r1_BeepOnState:
				microwave_closed_microwave_r1_Finished_r1_BeepOnState_react(true);
				break;
			case microwave_closed_microwave_r1_Finished_r1_BeepOffState:
				microwave_closed_microwave_r1_Finished_r1_BeepOffState_react(true);
				break;
			default:
				// $NullState$
			}
		}
		clearEvents();
	}
	public void exit() {
		exitSequence_Microwave();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case microwave_OpenDoor:
			return stateVector[0] == State.microwave_OpenDoor;
		case microwave_closed_microwave:
			return stateVector[0].ordinal() >= State.
					microwave_closed_microwave.ordinal()&& stateVector[0].ordinal() <= State.microwave_closed_microwave_r1_Finished_r1_BeepOffState.ordinal();
		case microwave_closed_microwave_r1_HighPower:
			return stateVector[0] == State.microwave_closed_microwave_r1_HighPower;
		case microwave_closed_microwave_r1_LowPower:
			return stateVector[0] == State.microwave_closed_microwave_r1_LowPower;
		case microwave_closed_microwave_r1_setTime:
			return stateVector[0] == State.microwave_closed_microwave_r1_setTime;
		case microwave_closed_microwave_r1_Cooking:
			return stateVector[0] == State.microwave_closed_microwave_r1_Cooking;
		case microwave_closed_microwave_r1_Init:
			return stateVector[0] == State.microwave_closed_microwave_r1_Init;
		case microwave_closed_microwave_r1_Finished:
			return stateVector[0].ordinal() >= State.
					microwave_closed_microwave_r1_Finished.ordinal()&& stateVector[0].ordinal() <= State.microwave_closed_microwave_r1_Finished_r1_BeepOffState.ordinal();
		case microwave_closed_microwave_r1_Finished_r1_BeepOnState:
			return stateVector[0] == State.microwave_closed_microwave_r1_Finished_r1_BeepOnState;
		case microwave_closed_microwave_r1_Finished_r1_BeepOffState:
			return stateVector[0] == State.microwave_closed_microwave_r1_Finished_r1_BeepOffState;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public void timeElapsed(int eventID) {
		timeEvents[eventID] = true;
		runCycle();
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public void raiseHigh() {
		sCInterface.raiseHigh();
	}
	
	public void raiseLow() {
		sCInterface.raiseLow();
	}
	
	public void raiseDigit(long value) {
		sCInterface.raiseDigit(value);
	}
	
	public void raiseTimer() {
		sCInterface.raiseTimer();
	}
	
	public void raiseStart() {
		sCInterface.raiseStart();
	}
	
	public void raiseStop() {
		sCInterface.raiseStop();
	}
	
	public void raiseOpen() {
		sCInterface.raiseOpen();
	}
	
	public void raiseClose() {
		sCInterface.raiseClose();
	}
	
	public long getPower() {
		return sCInterface.getPower();
	}
	
	public void setPower(long value) {
		sCInterface.setPower(value);
	}
	
	/* Entry action for state 'OpenDoor'. */
	private void entryAction_Microwave_OpenDoor() {
		sCInterface.operationCallback.stopCook();
		
		sCInterface.operationCallback.openDoor();
		
		sCInterface.operationCallback.display("Waiting");
	}
	
	/* Entry action for state 'HighPower'. */
	private void entryAction_Microwave_closed_microwave_r1_HighPower() {
		sCInterface.setPower(1);
		
		sCInterface.operationCallback.display("High");
	}
	
	/* Entry action for state 'LowPower'. */
	private void entryAction_Microwave_closed_microwave_r1_LowPower() {
		sCInterface.setPower(2);
		
		sCInterface.operationCallback.display("Low");
	}
	
	/* Entry action for state 'setTime'. */
	private void entryAction_Microwave_closed_microwave_r1_setTime() {
		setTimeVariable(0);
		
		sCInterface.operationCallback.clearDisplay();
	}
	
	/* Entry action for state 'Cooking'. */
	private void entryAction_Microwave_closed_microwave_r1_Cooking() {
		timer.setTimer(this, 0, (1 * 1000), true);
		
		setTimeVariable(((((timeVariable / 100) * 60)) + ((timeVariable % 100))));
	}
	
	/* Entry action for state 'Init'. */
	private void entryAction_Microwave_closed_microwave_r1_Init() {
		sCInterface.operationCallback.clearDisplay();
		
		sCInterface.operationCallback.closeDoor();
		
		sCInterface.operationCallback.stopCook();
	}
	
	/* Entry action for state 'Finished'. */
	private void entryAction_Microwave_closed_microwave_r1_Finished() {
		timer.setTimer(this, 1, (5 * 1000), false);
	}
	
	/* Entry action for state 'BeepOnState'. */
	private void entryAction_Microwave_closed_microwave_r1_Finished_r1_BeepOnState() {
		timer.setTimer(this, 2, (1 * 1000), false);
		
		sCInterface.operationCallback.display("Finished");
		
		sCInterface.operationCallback.beepOn();
	}
	
	/* Entry action for state 'BeepOffState'. */
	private void entryAction_Microwave_closed_microwave_r1_Finished_r1_BeepOffState() {
		timer.setTimer(this, 3, (1 * 1000), false);
		
		sCInterface.operationCallback.clearDisplay();
		
		sCInterface.operationCallback.beepOff();
	}
	
	/* Exit action for state 'Cooking'. */
	private void exitAction_Microwave_closed_microwave_r1_Cooking() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Finished'. */
	private void exitAction_Microwave_closed_microwave_r1_Finished() {
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'BeepOnState'. */
	private void exitAction_Microwave_closed_microwave_r1_Finished_r1_BeepOnState() {
		timer.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'BeepOffState'. */
	private void exitAction_Microwave_closed_microwave_r1_Finished_r1_BeepOffState() {
		timer.unsetTimer(this, 3);
	}
	
	/* 'default' enter sequence for state OpenDoor */
	private void enterSequence_Microwave_OpenDoor_default() {
		entryAction_Microwave_OpenDoor();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_OpenDoor;
	}
	
	/* 'default' enter sequence for state closed microwave */
	private void enterSequence_Microwave_closed_microwave_default() {
		enterSequence_Microwave_closed_microwave_r1_default();
	}
	
	/* 'default' enter sequence for state HighPower */
	private void enterSequence_Microwave_closed_microwave_r1_HighPower_default() {
		entryAction_Microwave_closed_microwave_r1_HighPower();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_closed_microwave_r1_HighPower;
		
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state LowPower */
	private void enterSequence_Microwave_closed_microwave_r1_LowPower_default() {
		entryAction_Microwave_closed_microwave_r1_LowPower();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_closed_microwave_r1_LowPower;
		
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state setTime */
	private void enterSequence_Microwave_closed_microwave_r1_setTime_default() {
		entryAction_Microwave_closed_microwave_r1_setTime();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_closed_microwave_r1_setTime;
		
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state Cooking */
	private void enterSequence_Microwave_closed_microwave_r1_Cooking_default() {
		entryAction_Microwave_closed_microwave_r1_Cooking();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_closed_microwave_r1_Cooking;
		
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state Init */
	private void enterSequence_Microwave_closed_microwave_r1_Init_default() {
		entryAction_Microwave_closed_microwave_r1_Init();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_closed_microwave_r1_Init;
		
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state Finished */
	private void enterSequence_Microwave_closed_microwave_r1_Finished_default() {
		entryAction_Microwave_closed_microwave_r1_Finished();
		enterSequence_Microwave_closed_microwave_r1_Finished_r1_default();
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state BeepOnState */
	private void enterSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOnState_default() {
		entryAction_Microwave_closed_microwave_r1_Finished_r1_BeepOnState();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_closed_microwave_r1_Finished_r1_BeepOnState;
		
		historyVector[1] = stateVector[0];
	}
	
	/* 'default' enter sequence for state BeepOffState */
	private void enterSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOffState_default() {
		entryAction_Microwave_closed_microwave_r1_Finished_r1_BeepOffState();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_closed_microwave_r1_Finished_r1_BeepOffState;
		
		historyVector[1] = stateVector[0];
	}
	
	/* 'default' enter sequence for region Microwave */
	private void enterSequence_Microwave_default() {
		react_Microwave__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_Microwave_closed_microwave_r1_default() {
		react_Microwave_closed_microwave_r1__entry_Default();
	}
	
	/* deep enterSequence with history in child r1 */
	private void deepEnterSequence_Microwave_closed_microwave_r1() {
		switch (historyVector[0]) {
		case microwave_closed_microwave_r1_HighPower:
			enterSequence_Microwave_closed_microwave_r1_HighPower_default();
			break;
		case microwave_closed_microwave_r1_LowPower:
			enterSequence_Microwave_closed_microwave_r1_LowPower_default();
			break;
		case microwave_closed_microwave_r1_setTime:
			enterSequence_Microwave_closed_microwave_r1_setTime_default();
			break;
		case microwave_closed_microwave_r1_Cooking:
			enterSequence_Microwave_closed_microwave_r1_Cooking_default();
			break;
		case microwave_closed_microwave_r1_Init:
			enterSequence_Microwave_closed_microwave_r1_Init_default();
			break;
		case microwave_closed_microwave_r1_Finished_r1_BeepOnState:
			entryAction_Microwave_closed_microwave_r1_Finished();
			deepEnterSequence_Microwave_closed_microwave_r1_Finished_r1();
			break;
		case microwave_closed_microwave_r1_Finished_r1_BeepOffState:
			entryAction_Microwave_closed_microwave_r1_Finished();
			deepEnterSequence_Microwave_closed_microwave_r1_Finished_r1();
			break;
		default:
			break;
		}
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_Microwave_closed_microwave_r1_Finished_r1_default() {
		react_Microwave_closed_microwave_r1_Finished_r1__entry_Default();
	}
	
	/* deep enterSequence with history in child r1 */
	private void deepEnterSequence_Microwave_closed_microwave_r1_Finished_r1() {
		switch (historyVector[1]) {
		case microwave_closed_microwave_r1_Finished_r1_BeepOnState:
			enterSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOnState_default();
			break;
		case microwave_closed_microwave_r1_Finished_r1_BeepOffState:
			enterSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOffState_default();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for state OpenDoor */
	private void exitSequence_Microwave_OpenDoor() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state closed microwave */
	private void exitSequence_Microwave_closed_microwave() {
		exitSequence_Microwave_closed_microwave_r1();
	}
	
	/* Default exit sequence for state HighPower */
	private void exitSequence_Microwave_closed_microwave_r1_HighPower() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state LowPower */
	private void exitSequence_Microwave_closed_microwave_r1_LowPower() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state setTime */
	private void exitSequence_Microwave_closed_microwave_r1_setTime() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Cooking */
	private void exitSequence_Microwave_closed_microwave_r1_Cooking() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Microwave_closed_microwave_r1_Cooking();
	}
	
	/* Default exit sequence for state Init */
	private void exitSequence_Microwave_closed_microwave_r1_Init() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Finished */
	private void exitSequence_Microwave_closed_microwave_r1_Finished() {
		exitSequence_Microwave_closed_microwave_r1_Finished_r1();
		exitAction_Microwave_closed_microwave_r1_Finished();
	}
	
	/* Default exit sequence for state BeepOnState */
	private void exitSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOnState() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Microwave_closed_microwave_r1_Finished_r1_BeepOnState();
	}
	
	/* Default exit sequence for state BeepOffState */
	private void exitSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOffState() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Microwave_closed_microwave_r1_Finished_r1_BeepOffState();
	}
	
	/* Default exit sequence for region Microwave */
	private void exitSequence_Microwave() {
		switch (stateVector[0]) {
		case microwave_OpenDoor:
			exitSequence_Microwave_OpenDoor();
			break;
		case microwave_closed_microwave_r1_HighPower:
			exitSequence_Microwave_closed_microwave_r1_HighPower();
			break;
		case microwave_closed_microwave_r1_LowPower:
			exitSequence_Microwave_closed_microwave_r1_LowPower();
			break;
		case microwave_closed_microwave_r1_setTime:
			exitSequence_Microwave_closed_microwave_r1_setTime();
			break;
		case microwave_closed_microwave_r1_Cooking:
			exitSequence_Microwave_closed_microwave_r1_Cooking();
			break;
		case microwave_closed_microwave_r1_Init:
			exitSequence_Microwave_closed_microwave_r1_Init();
			break;
		case microwave_closed_microwave_r1_Finished_r1_BeepOnState:
			exitSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOnState();
			exitAction_Microwave_closed_microwave_r1_Finished();
			break;
		case microwave_closed_microwave_r1_Finished_r1_BeepOffState:
			exitSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOffState();
			exitAction_Microwave_closed_microwave_r1_Finished();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_Microwave_closed_microwave_r1() {
		switch (stateVector[0]) {
		case microwave_closed_microwave_r1_HighPower:
			exitSequence_Microwave_closed_microwave_r1_HighPower();
			break;
		case microwave_closed_microwave_r1_LowPower:
			exitSequence_Microwave_closed_microwave_r1_LowPower();
			break;
		case microwave_closed_microwave_r1_setTime:
			exitSequence_Microwave_closed_microwave_r1_setTime();
			break;
		case microwave_closed_microwave_r1_Cooking:
			exitSequence_Microwave_closed_microwave_r1_Cooking();
			break;
		case microwave_closed_microwave_r1_Init:
			exitSequence_Microwave_closed_microwave_r1_Init();
			break;
		case microwave_closed_microwave_r1_Finished_r1_BeepOnState:
			exitSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOnState();
			exitAction_Microwave_closed_microwave_r1_Finished();
			break;
		case microwave_closed_microwave_r1_Finished_r1_BeepOffState:
			exitSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOffState();
			exitAction_Microwave_closed_microwave_r1_Finished();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_Microwave_closed_microwave_r1_Finished_r1() {
		switch (stateVector[0]) {
		case microwave_closed_microwave_r1_Finished_r1_BeepOnState:
			exitSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOnState();
			break;
		case microwave_closed_microwave_r1_Finished_r1_BeepOffState:
			exitSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOffState();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave_closed_microwave_r1__entry_Default() {
		enterSequence_Microwave_closed_microwave_r1_Init_default();
	}
	
	/* Default react sequence for deep history entry continue */
	private void react_Microwave_closed_microwave_r1_continue() {
		/* Enter the region with deep history */
		if (historyVector[0] != State.$NullState$) {
			deepEnterSequence_Microwave_closed_microwave_r1();
		} else {
			enterSequence_Microwave_closed_microwave_r1_Init_default();
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave_closed_microwave_r1_Finished_r1__entry_Default() {
		enterSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOnState_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave__entry_Default() {
		enterSequence_Microwave_closed_microwave_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean microwave_OpenDoor_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.close) {
					exitSequence_Microwave_OpenDoor();
					sCInterface.operationCallback.closeDoor();
					
					react_Microwave_closed_microwave_r1_continue();
				} else {
					if (sCInterface.stop) {
						exitSequence_Microwave_OpenDoor();
						react_Microwave__entry_Default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_closed_microwave_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.open) {
					exitSequence_Microwave_closed_microwave();
					sCInterface.operationCallback.openDoor();
					
					enterSequence_Microwave_OpenDoor_default();
				} else {
					if (sCInterface.stop) {
						exitSequence_Microwave_closed_microwave();
						react_Microwave__entry_Default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_closed_microwave_r1_HighPower_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_closed_microwave_react(try_transition)==false) {
				if (sCInterface.low) {
					exitSequence_Microwave_closed_microwave_r1_HighPower();
					enterSequence_Microwave_closed_microwave_r1_LowPower_default();
				} else {
					if (sCInterface.timer) {
						exitSequence_Microwave_closed_microwave_r1_HighPower();
						enterSequence_Microwave_closed_microwave_r1_setTime_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_closed_microwave_r1_LowPower_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_closed_microwave_react(try_transition)==false) {
				if (sCInterface.high) {
					exitSequence_Microwave_closed_microwave_r1_LowPower();
					enterSequence_Microwave_closed_microwave_r1_HighPower_default();
				} else {
					if (sCInterface.timer) {
						exitSequence_Microwave_closed_microwave_r1_LowPower();
						enterSequence_Microwave_closed_microwave_r1_setTime_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_closed_microwave_r1_setTime_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_closed_microwave_react(try_transition)==false) {
				if (sCInterface.start) {
					exitSequence_Microwave_closed_microwave_r1_setTime();
					sCInterface.operationCallback.cook();
					
					enterSequence_Microwave_closed_microwave_r1_Cooking_default();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			if (((sCInterface.digit) && (getTimeVariable()<1000))) {
				setTimeVariable((((timeVariable * 10)) + sCInterface.getDigitValue()));
				
				sCInterface.operationCallback.displayTime(getTimeVariable());
			}
		}
		return did_transition;
	}
	
	private boolean microwave_closed_microwave_r1_Cooking_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_closed_microwave_react(try_transition)==false) {
				if (getTimeVariable()==0) {
					exitSequence_Microwave_closed_microwave_r1_Cooking();
					sCInterface.operationCallback.stopCook();
					
					enterSequence_Microwave_closed_microwave_r1_Finished_default();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			if (timeEvents[0]) {
				setTimeVariable(getTimeVariable() - 1);
				
				sCInterface.operationCallback.displayTime(((((getTimeVariable() / 60) * 100)) + ((getTimeVariable() % 60))));
			}
		}
		return did_transition;
	}
	
	private boolean microwave_closed_microwave_r1_Init_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_closed_microwave_react(try_transition)==false) {
				if (sCInterface.high) {
					exitSequence_Microwave_closed_microwave_r1_Init();
					enterSequence_Microwave_closed_microwave_r1_HighPower_default();
				} else {
					if (sCInterface.low) {
						exitSequence_Microwave_closed_microwave_r1_Init();
						enterSequence_Microwave_closed_microwave_r1_LowPower_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_closed_microwave_r1_Finished_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_closed_microwave_react(try_transition)==false) {
				if (timeEvents[1]) {
					exitSequence_Microwave_closed_microwave_r1_Finished();
					sCInterface.operationCallback.beepOff();
					
					sCInterface.operationCallback.clearDisplay();
					
					enterSequence_Microwave_closed_microwave_r1_Init_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_closed_microwave_r1_Finished_r1_BeepOnState_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_closed_microwave_r1_Finished_react(try_transition)==false) {
				if (timeEvents[2]) {
					exitSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOnState();
					enterSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOffState_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_closed_microwave_r1_Finished_r1_BeepOffState_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_closed_microwave_r1_Finished_react(try_transition)==false) {
				if (timeEvents[3]) {
					exitSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOffState();
					enterSequence_Microwave_closed_microwave_r1_Finished_r1_BeepOnState_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
}
